services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # expose Redis for workers to connect

  controller:
    build: .
    container_name: controller
    ports:
      - "5000:5000"  # expose Flask app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
